# -*- coding: utf-8 -*-
"""machine learing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gfxy94Y-6LwIg4wD9b1im0wKH-sWEgQL
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv("/content/sample_data/indian-national-level-election.csv")

df.head()

df.info()

df.describe()

df.isnull().sum()

df['pc_name'].value_counts()

df.describe()

df.describe()

df.info()

df.info()

df.info()

df.describe()

df.dtypes

df.columns

print(df['pc_type'].value_counts(dropna=False))
print(df['cand_sex'].value_counts(dropna=False))

df['pc_type'].fillna(df['pc_type'].mode()[0], inplace=True)
df['cand_sex'].fillna(df['cand_sex'].mode()[0], inplace=True)

df = pd.get_dummies(df, columns=['pc_type', 'cand_sex'], drop_first=True)